spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE


  liquibase:
    change-log: classpath:/db/changelog/changelog-h2-master.yaml
    enabled: true
  jpa:
    database: h2
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        dialect: org.hibernate.dialect.H2Dialect