GET http://localhost:8080/api/items/v1/item
Accept: application/json

###

GET http://localhost:8080/api/items/v1/item/2
Accept: application/json

###

POST http://localhost:8080/api/items/v1/item
Content-Type: application/json

{
  "id": 1,
  "category": "nieuws",
  "title": "Beroepingswerk",
  "author": "Jan Langeraar",
  "published": "2023-04-01T08:00:00+02:00",
  "content": "Op dit moment is er over het beroepingswerk niets te melden"
}

###


POST http://localhost:8080/api/items/v1/item
Content-Type: application/json

{
  "id": 1,
  "category": "kerkdienst",
  "title": "Beroepingswerk",
  "author": "Jan Langeraar",
  "published": "2023-04-02T08:00:00+02:00",
  "content": "Op dit moment is er over het beroepingswerk niets te melden"
}

###

POST http://localhost:8080/api/items/v1/item
Content-Type: application/json

{
  "id": 2,
  "category": "markt",
  "title": "Skelter",
  "author": "Jan Noppe",
  "content": "Doordat de kinderen groter worden is het nu mogelijk om een mooie skelter te kopen. Vraagprijs 50 euro"
}


###

POST http://localhost:8080/api/items/v1/item
Content-Type: application/json

{
  "id": 3,
  "category": "vraag",
  "author": "Jan de Graaf",
  "content": "Voor vluchteling die naar cursus moet een (gebruikte) fiets gevraagd"
}


###

DELETE http://localhost:8080/api/items/v1/items/1

###

DELETE http://localhost:8080/api/items/v1/items/2

###

DELETE http://localhost:8080/api/items/v1/items/3

###