GET http://localhost:8090/api/persons/v1/person
Accept: application/json

###

POST http://localhost:8090/api/persons/v1/person
Content-Type: application/json

{
  "id": 1,
  "voornaam": "Jan",
  "tussenvoegsel": "de",
  "achternaam": "Vries",
  "created": "2023-04-01T08:00",
  "state": "created",
  "username": "mark@gmail.com",
  "password": "123456",
  "roles": [
    {
      "name": "USER"
    }
  ]
}

###

POST http://localhost:8090/api/persons/v1/person
Content-Type: application/json

{
  "id": 2,
  "voornaam": "Frans",
  "tussenvoegsel": null,
  "achternaam": "Cortenbach",
  "created": "2023-04-01T08:00",
  "state": "created",
  "username": "frans@gmail.com",
  "password": "123456",
  "roles": [
    {
      "name": "ADMIN"
    },
    {
      "name": "USER"
    }
  ]
}

###

POST http://localhost:8090/api/persons/v1/person
Content-Type: application/json

{
  "id": 3,
  "voornaam": "Asterix",
  "tussenvoegsel": "van der",
  "achternaam": "Laan",
  "created": "2023-05-01T08:00",
  "state": "created",
  "username": "asterix@gmail.com",
  "password": "123456",
  "roles": [
    {
      "name": "ADMIN"
    },
    {
      "name": "DATABASE"
    },
    {
      "name": "EDITOR"
    },
    {
      "name": "USER"
    }
  ]
}

###

GET http://localhost:8090/api/persons/v1/person
Accept: application/json

###

GET http://localhost:8090/api/persons/v1/person/1
Accept: application/json

###


GET http://localhost:8090/api/persons/v1/person/2
Accept: application/json

###

DELETE http://localhost:8090/api/persons/v1/person/1

###

DELETE http://localhost:8090/api/persons/v1/person/2

###


GET http://localhost:8090/api/persons/v1/role
Accept: application/json

###

GET http://localhost:8090/api/persons/v1/role/1
Accept: application/json

###