GET http://localhost:8090/api/persons/v1/person
Accept: application/json

###

POST http://localhost:8090/api/persons/v1/person
Content-Type: application/json

{
  "id": 1,
  "voornaam": "Jan",
  "tussenvoegsel": "de",
  "achternaam": "Vries",
  "created": "2023-04-01T08:00",
  "state": "created"
}

###

POST http://localhost:8090/api/persons/v1/person
Content-Type: application/json

{
  "id": 2,
  "voornaam": "Frans",
  "tussenvoegsel": null,
  "achternaam": "Cortenbach",
  "created": "2023-04-01T08:00",
  "state": "created"
}

###

GET http://localhost:8090/api/persons/v1/person
Accept: application/json

###

GET http://localhost:8090/api/persons/v1/person/1
Accept: application/json

###


GET http://localhost:8090/api/persons/v1/person/2
Accept: application/json

###

DELETE http://localhost:8090/api/persons/v1/person/1

###

DELETE http://localhost:8090/api/persons/v1/person/2

###
