
GET http://localhost:8080/api/items/v1/items
Accept: application/json

###

POST http://localhost:8080/api/items/v1/items
Content-Type: application/json

{
  "category": "nieuws",
  "title": "Beroepingswerk",
  "author": "Jan Langeraar",
  "published": "2023-04-01T08:00",
  "content": "Op dit moment is er over het beroepingswerk niets te melden"
}

###
POST http://localhost:8080/api/items/v1/items
Content-Type: application/json

{
  "category": "markt",
  "title": "Skelter",
  "author": "Jan Noppe",

  "content": "Doordat de kinderen groter worden is het nu mogelijk om een mooie skelter te kopen. Vraagprijs 50 euro"
}


###