--- Database personen
SELECT 'SELECT * FROM PERSON;';
SELECT * FROM PERSON;

SELECT 'SELECT * FROM ROLE;';
SELECT * FROM ROLE;

SELECT 'SELECT * FROM PERSON_GRANTS;';
SELECT * FROM PERSON_GRANTS;

SELECT 'PERSON WITH ROLES';
SELECT P.*, R.* FROM PERSON P, PERSON_GRANTS PG, ROLE R
WHERE P.ID = PG.PERSON_ID AND PG.ROLE_ID = R.ID
ORDER BY P.ID, R.ID;